controller_joint_names: ['', 'castersupport1', 'caster1', 'castersupport2', 'caster2', 'gear1', 'board1', 'servo1', 'board5', 'board3', 'top', 'servo2', 'hand1', 'gear3', 'hand2', 'stick1', 'stick2', ]
